name: gcp_cloud_tasks
description: A small package to make interacting with Google Cloud Tasks easier.
version: 0.1.0-dev.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  current_gcp_project: ^0.0.1
  googleapis: ^11.3.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
